#!/usr/bin/env python3
"""Regenerates hooks/chimes.ts: two short dings as base64 WAV. Run after changing a tone."""
import base64, io, math, pathlib, struct, wave
RATE = 22050
def ding(freq, seconds=1.1, decay=4.0):
    n = int(RATE * seconds)
    return [0.5 * math.exp(-decay * i / RATE) * (math.sin(2 * math.pi * freq * i / RATE) + 0.2 * math.sin(2 * math.pi * 2 * freq * i / RATE)) for i in range(n)]
def wav_b64(buf):
    peak = max(1e-6, max(abs(v) for v in buf))
    bio = io.BytesIO()
    with wave.open(bio, "wb") as w:
        w.setnchannels(1); w.setsampwidth(2); w.setframerate(RATE)
        w.writeframes(b"".join(struct.pack("<h", int(max(-1, min(1, v / peak * 0.6)) * 32767)) for v in buf))
    return base64.b64encode(bio.getvalue()).decode()
root = pathlib.Path(__file__).resolve().parent.parent
(root / "hooks/chimes.ts").write_text(
    "// The two chimes as WAV bytes (22 kHz mono, one note, ringing about a second), generated by scripts/make-chimes.py.\n"
    "// Kept as text so the plugin holds no binary files.\n"
    f'export const CHIME_ON = "{wav_b64(ding(880.0))}"\n\n'
    f'export const CHIME_OFF = "{wav_b64(ding(523.25))}"\n')
print("chimes.ts written")
